default:
	g++ ./main.cpp -o main --std=c++23 -O3
	time ./main < ./input.txt
test:
	bear -- clang++ ./main.cpp --std=c++23
	g++ ./main.cpp -o main --std=c++23
	cat sample.txt | ./main
bigboy:
	g++ ./main.cpp -o main --std=c++23 -O3
	time ./main < ./input.txt
